set number of parallel jobs; fix #23
ViCCo-Group/frrsa pull request #29
Opened 2022-04-19 09:43 UTC by hahahannes

2022-04-19 10:34 UTC, PhilippKaniuth requested changes
You declare the parameter's type to be `int`, but the option "max" can only by assigned as a string. This would lead to a TypeError later when checking `parallel > 1`. 

I think either declare the parameter to be a `string` or treat some very large integer as the max-option.

2022-04-19 10:34 UTC, PhilippKaniuth commented on frrsa/fitting/crossvalidation.py
>      parallel : bool
Also, could you escalate the chaging of the type? :)

2022-04-19 10:36 UTC, PhilippKaniuth commented on frrsa/fitting/crossvalidation.py
> +    parallel : int, optional
Type should be `str` or change the "max" option to large integer.

2022-04-19 10:37 UTC, PhilippKaniuth commented on frrsa/fitting/crossvalidation.py
> +    if parallel > 1:
This would throw an error if `parallel="max"`

2022-04-19 11:24 UTC, hahahannes commented
ah yes, thanks for spotting! that implementation was bit rushed @PhilippKaniuth

2022-04-19 13:54 UTC, PhilippKaniuth commented
Thanks! But line 350 would still throw an error, right? It would try to check whether the string is bigger than 1. This would throw a TypeError as the operand `>` is not supported between `str` and `int`.

And in 297 `parallel` is still declared and int? Default value of `parallel` in `frrsa` is also an int. Or am I being thick here?:D

2022-04-19 14:07 UTC, hahahannes commented
I moved the conversion to line 190. Then  start_outer_cross_validation expects only integers (no max anymore). Thought this might be cleaner instead of str/int type checking in start_outer_cross_validation

2022-04-19 15:02 UTC, PhilippKaniuth commented
Apologies, I didn't realize that, that's nice.

However, we can't unambiguously indicate the type then, right? `str` is wrong if the user doesn't input `"max"`, and `int` is wrong if s/he does input `"max"`. And if the user inputs say 2 as a string (since we declared it to be input as a string) there will be the TypeError.

While I agree that the conversion is 190 is nice, I think I would favor making it as easy as possible for the user; which would be to unambiguously indicate the type as `str` and type check it and/or transform it once. What do you think? It could be done easily be amending the if-statement in 190:

```python
if parallel == 'max':
  parallel = psutil.cpu_count(logical=False)
else:
  parallel = int(parallel)
  ```

2022-04-19 15:25 UTC, hahahannes commented
aggree! otherwise the documentation would be wrong

2022-04-20 09:30 UTC, PhilippKaniuth approved these changes

2022-04-20 09:31 UTC, merged